In [3]:
# Numpy Tutorials
# Numpy is a general purpose array-processing package.It provides a high performance multidimensional array object,and tools for working with these arrays.It is the fundamental package for scientific computing with python.

# Array: An array is a data structure that stores values of same data type. In Python,this is the main difference between array and lists. While lists can contain values corresponding to different data types,arrays in python can only contain values corresponding to same data type.


In [ ]:
## initially lets import numpy

In [5]:
import numpy as np
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [6]:
type(arr) # check the data type

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape

(5,)

In [20]:
## multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [12]:
arr.shape

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [14]:
## Indexing
# Accessing the array element

arr=np.array([1,2,3,4,5,6,7,8,9])

np.int64(4)

In [21]:
## in multiple array
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [26]:
arr[:,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [27]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [30]:
arr[1:,2:4]

array([[4, 5],
       [5, 6]])

In [33]:
arr=np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr=np.arange(0,10,2)  ## step=2

In [36]:
arr

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [39]:
## copy() function and broadcasting

arr[3:]=100

In [41]:
arr

array([  0,   2,   4, 100, 100])

In [47]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[3:]=100
print(arr1)

[  1   2   3 100 100 100 100 100 100]


In [48]:
### Some conditions very useful in Exploratory Data Analysis
val=2
arr

array([  0,   2,   4, 100, 100])

In [49]:
arr*2

array([  0,   4,   8, 200, 200])

In [50]:
arr/2

array([ 0.,  1.,  2., 50., 50.])

In [51]:
arr%2

array([0, 0, 0, 0, 0])

In [52]:
arr<2

array([ True, False, False, False, False])

In [56]:
arr[arr<500]  ## to get exact element which are less than values

array([  0,   2,   4, 100, 100])

In [57]:
## create array and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
np.ones(4) ## np.ones create an array where all the elements are basically replace by one

array([1., 1., 1., 1.])

In [59]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [62]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
## random distribution :: It Selects some random values of the given sheet
np.random.rand(3,3)

array([[0.00222838, 0.04167235, 0.00315856],
       [0.22135235, 0.20886305, 0.12996626],
       [0.41892853, 0.05522925, 0.02578536]])

In [68]:
arr_ex=np.random.randn(4,4) ## it selects variable based on standard normal distribution
arr_ex

array([[ 2.14555296e-01, -1.47744880e-01, -1.23188814e+00,
         1.13294054e+00],
       [ 6.83611737e-01,  9.59064966e-01,  9.48900687e-02,
         1.68901379e-03],
       [ 5.66842027e-01,  1.41295103e+00, -4.71097461e-01,
         4.08661170e-01],
       [-8.10705939e-02, -5.31570508e-01, -2.23254330e+00,
        -8.55206787e-01]])

In [70]:
np.random.randint(0,100,8)


array([59, 92, 71, 56, 83, 16,  1, 67], dtype=int32)

In [71]:
np.random.randint(0,100,8).reshape(2,4)

array([[62, 48, 94,  2],
       [95, 38, 46, 57]], dtype=int32)

In [72]:
np.random.random_sample((1,5))

array([[0.36093916, 0.61124334, 0.29581433, 0.16925605, 0.53939857]])